### ISSUE TITLE
Incompatilbe to tilt 2.x

### ISSUE THREAD

**Issue by miyagawa** [eagletmt/faml#23]
When you run faml with tilt 2.x, you get the following error:

```
/Users/miyagawa/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/tilt-2.0.1/lib/tilt/haml.rb:2:in `require': cannot load such file -- haml (LoadError)
	from /Users/miyagawa/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/tilt-2.0.1/lib/tilt/haml.rb:2:in `<top (required)>'
	from /Users/miyagawa/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/faml-0.2.15/lib/faml/tilt.rb:2:in `require'
	from /Users/miyagawa/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/faml-0.2.15/lib/faml/tilt.rb:2:in `<top (required)>'
	from /Users/miyagawa/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/faml-0.2.15/lib/faml.rb:2:in `require'
	from /Users/miyagawa/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/faml-0.2.15/lib/faml.rb:2:in `<top (required)>'
	from /Users/miyagawa/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.10.5/lib/bundler/runtime.rb:76:in `require'
	from /Users/miyagawa/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.10.5/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from /Users/miyagawa/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.10.5/lib/bundler/runtime.rb:72:in `each'
	from /Users/miyagawa/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.10.5/lib/bundler/runtime.rb:72:in `block in require'
	from /Users/miyagawa/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.10.5/lib/bundler/runtime.rb:61:in `each'
	from /Users/miyagawa/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.10.5/lib/bundler/runtime.rb:61:in `require'
	from /Users/miyagawa/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.10.5/lib/bundler.rb:134:in `require'
	from /Users/miyagawa/dev/foo/config/application.rb:16:in `<top (required)>'
	from /Users/miyagawa/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.2/lib/rails/commands/commands_tasks.rb:141:in `require'
	from /Users/miyagawa/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.2/lib/rails/commands/commands_tasks.rb:141:in `require_application_and_environment!'
	from /Users/miyagawa/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.2/lib/rails/commands/commands_tasks.rb:67:in `console'
	from /Users/miyagawa/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.2/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/miyagawa/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.2/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

Looks like there's an upstream change in tilt where requiring 'tilt/haml' will immediately require 'haml', which is not in the Gemfile. https://github.com/rtomayko/tilt/commit/432ae805c21a78e1eea0727cd5daf7530a970381

**Comment by eagletmt** [comment]
Released v0.2.16 https://rubygems.org/gems/faml/versions/0.2.16
Thank you for reporting issue!
